# Generated by Django 3.0.6 on 2020-05-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_title', models.CharField(max_length=100)),
                ('wish_description', models.CharField(max_length=300)),
                ('pic', models.ImageField(upload_to='wish/images/')),
            ],
        ),
    ]
