# Generated by Django 3.0.6 on 2020-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wish_description',
            field=models.TextField(),
        ),
    ]
